---

- name: yum | smokeping and dependencies install
  yum: name="{{item}}" state=present update_cache=yes
  with_items: "{{ smokeping_pkg }}"

- name: yum | Ensure httpd is running and enabled on boot.
  service: name=httpd state=started enabled=yes

## FIXME! not idempotent
#- selinux: state=disabled
- selinux: policy=targeted state=permissive

