---

- name: yum | smokeping and dependencies install
  yum: name="{{ smokeping_pkg }}" state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success

- name: yum | Ensure httpd is running and enabled on boot.
  service: name=httpd state=started enabled=yes

## FIXME! not idempotent
#- selinux: state=disabled
- selinux: policy=targeted state=permissive
